export const MIME_LUT = [
    [
        /\.webp$/i,
        'image/webp'
    ],
    [
        /\.m3u8$/i,
        'application/vnd.apple.mpegurl'
    ],
    [
        /\.ts$/i,
        'video/mp2t'
    ],
    [
        /\.m4s$/i,
        'video/iso.segment'
    ],
    [
        /\.mp4$/i,
        'video/mp4'
    ],
    [
        /\.txt$/i,
        'text/plain'
    ],
    [
        /\.xml$/i,
        'text/xml'
    ],
    [
        /\.key$/i,
        'binary/octet-stream'
    ],
    [
        /\.mpd$/i,
        'application/dash+xml'
    ],
]